### ISSUE TITLE
Could not pass event PlayerDeathEvent to SkyPvP v1.0

### ISSUE THREAD

**Issue by AleNight** [0-fps/SkyPvP-Remake#1]
Uhm.. Hello.. I'm using SkyPvP on a minecraft server 1.15.2
When I die or when someone kills me this happen:
--
```
[16:11:38 ERROR]: Could not pass event PlayerDeathEvent to SkyPvP v1.0
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:614) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:983) ~[?:?]
        at me.fps.skypvp.events.PlayerKills.KillPlayer(PlayerKills.java:33) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor17.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Purpur-606]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Purpur-606]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Purpur-606]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Purpur-606]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:793) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityPlayer.die(EntityPlayer.java:626) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1154) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:837) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:788) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityLiving.af(EntityLiving.java:1864) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.Entity.doVoidDamage(Entity.java:599) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.Entity.performVoidDamage(Entity.java:519) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:502) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:246) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:444) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2352) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:189) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:465) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:160) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:422) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1437) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1263) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:987) ~[patched_1.15.2.jar:git-Purpur-606]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
--
I dont know why. But I use this plugins: Citizens, Hibernate, HolographicDisplays, LiteBans, Maintenance, PlaceholderAPI, PlayerKits, Shopkeepers, SimpleRename, SkinsRestorer, SkyPvP*, TrMenu, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard, XConomy
-- 
I use a not dedicated (25565) port. I dont know if this is the bug but query-port is on 25565
--
Have a nice day! :D

**Comment by 0-fps** [comment]
You need change you world from de config files creation, if you want can change the code of PlayerEntry.java, you can.

Only this fix if you change your world using multiverse or a plugin like this
